benchmark:
  max_latency_ms: 10
  min_accuracy: 0.95
deployment:
  git_repo: https://github.com/shinshawcs/mnist_model_pipeline.git
  pr_branch: dev-mnist-model
model:
  name: mnist_model
  onnx_path: models/mnist_model.onnx
  path: models/mnist_model.pt
  version: v1
